### ISSUE TITLE
PTBdata

### ISSUE THREAD

**Issue by Wang-YaoJie** [lvyiwei1/StylePTB#2]
Hi! I saw that you imported PTBdata in a few different files (i.e. InformationDeletion.py, I was wondering if that is an additional package that you wrote?Looking forward to your reply!

**Comment by lvyiwei1** [comment]
Yes there was supposed to be another file called PTBdata.py... I will add that to the repo on Thursday (since it's stored on a local hardware and I will not be back until Thursday). I am very sorry for the delay.

**Comment by Wang-YaoJie** [comment]
Thanks a lot!

**Comment by carolinedivittorio** [comment]
Hi - I was hoping to follow up on the PTBdata.py file. Would it be possible for you to upload it to the repo? Thank you so much!

**Comment by lvyiwei1** [comment]
Sorry for the delay. It is uploaded now.

**Comment by carolinedivittorio** [comment]
Thank you so much - this is awesome!
